from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib.utils import ImageReader
from PIL import Image
import io
import os
import pandas as pd
from datetime import datetime
try:
    # optional: load .env if present
    from dotenv import load_dotenv
    load_dotenv()
except Exception:
    pass


def generate_proof_pdf(file_bytes: bytes, filename: str, task_description: str, log_path: str = "proof_log.csv") -> bytes:
    """Generate a proof PDF from image bytes and log the entry.

    Returns PDF bytes.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    pdf_buffer = io.BytesIO()
    c = canvas.Canvas(pdf_buffer, pagesize=letter)
    page_width, page_height = letter
    margin = 50
    y = page_height - margin

    c.setFont("Helvetica-Bold", 16)
    c.drawString(margin, y, "SnapProof – Timestamped Proof")
    c.setFont("Helvetica", 11)
    y -= 30
    c.drawString(margin, y, f"Task: {task_description}")
    y -= 18
    c.drawString(margin, y, f"Timestamp: {timestamp}")
    y -= 18
    c.drawString(margin, y, f"Filename: {filename}")
    y -= 24

    try:
        img = Image.open(io.BytesIO(file_bytes)).convert("RGB")
        img_w, img_h = img.size

        max_w = page_width - 2 * margin
        max_h = 300
        scale = min(max_w / img_w, max_h / img_h, 1.0)
        draw_w = img_w * scale
        draw_h = img_h * scale

        img_reader = ImageReader(img)
        c.drawImage(img_reader, margin, y - draw_h, width=draw_w, height=draw_h)
        y -= draw_h + 20
    except Exception as e:
        y -= 10
        c.setFont("Helvetica-Oblique", 10)
        c.drawString(margin, y, f"(Could not embed image: {e})")
        y -= 12

    c.setFont("Helvetica", 9)
    c.drawString(margin, 40, "Generated by SnapProof")

    c.showPage()
    c.save()
    pdf_buffer.seek(0)
    pdf_bytes = pdf_buffer.getvalue()

    # Attempt Google Sheets logging if enabled, otherwise fall back to CSV
    entry = {"timestamp": timestamp, "task": task_description, "filename": filename}
    use_sheets = os.getenv("USE_SHEETS", "false").lower() in ("1", "true", "yes")
    if use_sheets:
        try:
            log_to_sheets(entry)
        except Exception:
            # if sheets logging fails, fall back to CSV
            try:
                if os.path.exists(log_path):
                    df = pd.read_csv(log_path)
                    df = pd.concat([df, pd.DataFrame([entry])], ignore_index=True)
                else:
                    df = pd.DataFrame([entry])
                df.to_csv(log_path, index=False)
            except Exception:
                pass
    else:
        try:
            if os.path.exists(log_path):
                df = pd.read_csv(log_path)
                df = pd.concat([df, pd.DataFrame([entry])], ignore_index=True)
            else:
                df = pd.DataFrame([entry])
            df.to_csv(log_path, index=False)
        except Exception:
            # If logging fails, ignore but do not break PDF generation
            pass

    return pdf_bytes


def log_to_sheets(entry: dict, sheet_id: str = None, sheet_name: str = "Sheet1", creds_path: str = None) -> bool:
    """Append an entry (dict with keys timestamp, task, filename) to a Google Sheet.

    Environment variables used when parameters are omitted:
      - GOOGLE_CREDENTIALS: path to service account JSON (default: credentials.json)
      - GOOGLE_SHEETS_ID: spreadsheet ID (from its URL)

    Returns True on success, raises on failure.
    """
    try:
        import gspread
        from oauth2client.service_account import ServiceAccountCredentials
    except Exception as e:
        raise RuntimeError("gspread and oauth2client are required for Google Sheets logging") from e

    if creds_path is None:
        creds_path = os.getenv("GOOGLE_CREDENTIALS", "credentials.json")
    if sheet_id is None:
        sheet_id = os.getenv("GOOGLE_SHEETS_ID")
    if not sheet_id:
        raise ValueError("Google Sheets ID not provided. Set GOOGLE_SHEETS_ID env var or pass sheet_id")

    scope = [
        "https://www.googleapis.com/auth/spreadsheets",
        "https://www.googleapis.com/auth/drive",
    ]
    creds = ServiceAccountCredentials.from_json_keyfile_name(creds_path, scope)
    gc = gspread.authorize(creds)

    # Open spreadsheet and worksheet
    sh = gc.open_by_key(sheet_id)
    try:
        worksheet = sh.worksheet(sheet_name)
    except Exception:
        worksheet = sh.add_worksheet(title=sheet_name, rows="1000", cols="10")

    row = [entry.get("timestamp", ""), entry.get("task", ""), entry.get("filename", "")]
    worksheet.append_row(row, value_input_option="USER_ENTERED")
    return True


def generate_multipage_proof_pdf(photos: list, statement: str) -> bytes:
    """Generate a multi-page PDF containing a statement and a page per photo.

    photos: list of dicts with keys 'bytes' and 'filename'
    statement: user statement text
    Returns PDF bytes.
    """
    from reportlab.pdfgen import canvas
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.utils import ImageReader

    pdf_buffer = io.BytesIO()
    c = canvas.Canvas(pdf_buffer, pagesize=letter)
    page_width, page_height = letter
    margin = 50

    # First page: statement
    y = page_height - margin
    c.setFont("Helvetica-Bold", 16)
    c.drawString(margin, y, "SnapProof – Statement")
    c.setFont("Helvetica", 11)
    y -= 30
    # Wrap statement text
    text_obj = c.beginText(margin, y)
    text_obj.setFont("Helvetica", 11)
    for line in statement.splitlines():
        text_obj.textLine(line)
    c.drawText(text_obj)
    c.showPage()

    # One page per photo, include label and timestamp
    for idx, p in enumerate(photos):
        try:
            img = Image.open(io.BytesIO(p["bytes"])).convert("RGB")
            img_w, img_h = img.size
            max_w = page_width - 2 * margin
            max_h = page_height - 2 * margin - 40  # leave space for label
            scale = min(max_w / img_w, max_h / img_h, 1.0)
            draw_w = img_w * scale
            draw_h = img_h * scale
            img_reader = ImageReader(img)

            # Draw label at the top
            c.setFont("Helvetica-Bold", 12)
            label = f"Photo {idx+1}: {p.get('filename','')}"
            timestamp = p.get('timestamp', '')
            if timestamp:
                label = f"{label} — {timestamp}"
            c.drawString(margin, page_height - margin + 5, label)

            x = (page_width - draw_w) / 2
            y = (page_height - draw_h) / 2 - 10
            c.drawImage(img_reader, x, y, width=draw_w, height=draw_h)
            c.showPage()
        except Exception:
            # skip problematic images
            continue

    c.save()
    pdf_buffer.seek(0)
    return pdf_buffer.getvalue()
